apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar-nginx
        image: registry1.lab-1.cloud.local/nginx:1.12.2
        resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "2Mi"
            cpu: "5m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx
    volumes:
      - name: nginx-conf
        configMap:
          name: nginx-configmap
